wandb_version: 1

T_0:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: epoch
    - 1: Train Accuracy
      5: 1
      6:
      - 1
      - 3
    - 1: Valid Accuracy
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss
      5: 1
      6:
      - 1
      - 3
    - 1: Valid Loss
      5: 1
      6:
      - 1
      - 3
    - 1: Train-Vlaid accuracy
      5: 1
      6:
      - 1
      - 3
    python_version: 3.10.4
    start_time: 1665065708.66919
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 18
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 1
      - 2
      - 7
      - 17
      - 23
      - 37
      4: 3.10.4
      5: 0.13.1
      8:
      - 1
      - 5
accum_iter:
  desc: null
  value: 2
device:
  desc: null
  value: cuda:0
epochs:
  desc: null
  value: 50
fold_num:
  desc: null
  value: 5
img_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0001
min_lr:
  desc: null
  value: 1.0e-06
model:
  desc: null
  value: efficientnet_lite0
model_path:
  desc: null
  value: ./models
num_workers:
  desc: null
  value: 0
seed:
  desc: null
  value: 0
train_bs:
  desc: null
  value: 10
valid_bs:
  desc: null
  value: 10
verbose_step:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 1.0e-05
